<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <p class="footer-header"><strong><?=$this->transEsc('Other Services')?></strong></p>
      <ul class="footer-list">
	      <li><a href="https://libfs3.simmons.edu/illiad/" target="_blank">Interlibrary Loan</a></li>
	      <li><a href="https://www.simmons.edu/library/resources/purchase" target="_blank">Request a Purchase</a></li>
              <li><a href="https://www.simmons.edu/library/resources/other-libraries" target="_blank">Other Libraries</a></li>
            
           </li>
      </ul>
    </div>
    <div class="footer-column">
      <p class="footer-header"><strong><?=$this->transEsc('Search Options')?></strong></p>
      <ul class="footer-list">
	<li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse')?></a></li>
	<!--<li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse by Call Number')?></a></li>-->
	<li><a href="<?=$this->url('browse-home')?>">Guided Call Number Browse</a></li>
	<li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
       <!-- <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>-->
        <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <p class="footer-header"><strong><?=$this->transEsc('Contact')?></strong></p>
      <ul class="footer-list">
	<li><a href="mailto:reference@simmons.edu"><i class="fa fa-envelope" aria-hidden="true"></i> reference@simmons.edu</a></li>
 <li>
<!--CHAT START--><!-- async chat button script --><script type="text/javascript"><!--//--><![CDATA[// ><!--

<!--//--><![CDATA[// ><!--

<!--//--><![CDATA[// ><!--

//<![CDATA[
  (function() {
    function async_load(){
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'https://libraryh3lp.com/js/libraryh3lp.js?multi';
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    }
  window.attachEvent ? window.attachEvent('onload', async_load) : window.addEventListener('load', async_load, false);
  })();
  //]]]]]]]]><![CDATA[><![CDATA[><![CDATA[>

//--><!]]]]]]><![CDATA[><![CDATA[>

//--><!]]]]><![CDATA[>

//--><!]]></script><script type="text/javascript"><!--//--><![CDATA[// ><!--

<!--//--><![CDATA[// ><!--

<!--//--><![CDATA[// ><!--

function newWindow() {
    window.open("https://libraryh3lp.com/chat/beatleyreference@chat.libraryh3lp.com?skin=12778&amp;theme=gtalk&amp;title=Simmons+Library&amp;identity=Librarian&amp;sound=true", "_blank", "toolbar=yes, scrollbars=yes, resizable=yes, top=0, left=0, width=250, height=385");
}

//--><!]]]]]]><![CDATA[><![CDATA[>

//--><!]]]]><![CDATA[>

//--><!]]></script>
<div class="libraryh3lp" jid="beatleyreference@chat.libraryh3lp.com" style="display: none;"><a href="#" onclick="window.open('https://libraryh3lp.com/chat/beatleyreference@chat.libraryh3lp.com?skin=12778&amp;theme=gtalk&amp;title=Beatley+Reference&amp;identity=Librarian&amp;sound=true', 'chat', 'resizable=1,width=230,height=372'); return false;"><i class="fa fa-commenting-o" aria-hidden="true"></i> Chat Now</a> </div>

<div class="libraryh3lp"><i class="fa fa-commenting" aria-hidden="true"></i> Chat is offline </div>
<!--CHAT END-->

</li>
<li><a href="tel:617-521-2786"><i class="fa fa-phone" aria-hidden="true"></i> (617)-521-2786</a></li>
<li><a href="https://www.simmons.edu/library/about/contact-us/meet-librarian" target="_blank"><i class="fa fa-calendar" aria-hidden="true"></i> Meet with a librarian</a></li>
      </ul>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>
