<div id="authcontainer">

<?php if (isset($_GET["ilsauth"])):?>
<?php $methods = $this->auth()->getManager()->getSelectableAuthOptions(); ?>
<?php else: ?>
<?php $methods = ["Shibboleth"]; ?>
<?php endif; ?>

<?php $count = count($methods); ?>
<?php foreach ($methods as $loop => $method):?>
  <div class="authmethod<?=$loop?> span<?=floor(12 / $count) ?>">
    <?php $this->auth()->getManager()->setAuthMethod($method) ?>
    <?=$this->auth()->getLoginDesc() ?>
    <?=$this->auth()->getLogin() ?>
  </div>
<?php endforeach ?>
</div>
<?php $this->auth()->getManager()->setAuthMethod('ChoiceAuth') ?>
