<?php
    // Set up page title:
    $this->headTitle($this->translate('Reserves Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Reserves') . '</li>';

    // Convenience variables:
    $reservesLookfor = $this->params->getDisplayQuery();

    //Remove basic search from Course Reserves:
    $this->layout()->searchbox = false;

    $this->searchClassId = 'SolrReserves';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h3><?=$this->transEsc('Search For Courses with Reserves')?></h3>
  <form class="form-inline" method="get" name="reservesSearchForm">
    <label for="reservesSearchForm_lookfor"><?=$this->transEsc("Your search terms")?></label>
    <input id="reservesSearchForm_lookfor" type="text" name="lookfor" size="40" value="<?=$this->escapeHtmlAttr($reservesLookfor)?>" <?=$this->searchOptions('SolrReserves')->autocompleteEnabled() ? ' class="autocomplete searcher:SolrReserves type:Reserves"' : ''?> />
    <input class="reserves-btn btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc("Find")?>"/>
  </form>
  <script type="text/javascript">$("#reservesSearchForm_lookfor").focus()</script>

  <div class="resulthead">
    <div class="pull-left flip">
      <?php $qtime = $this->results->getQuerySpeed(); ?>
      <?php if (($recordTotal = $this->results->getResultTotal()) > 0): ?>
        <?php
          $transParams = [
            '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
            '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
            '%%total%%' => $this->localizedNumber($recordTotal),
            '%%lookfor%%' => $this->escapeHtml($reservesLookfor)
          ];
        ?>
        <?=$this->translate('showing_results_of_for_html', $transParams); ?><?php if($qtime): ?>,<?php endif; ?>
      <?php endif; ?>
     <!-- <?php if ($qtime): ?>
        <?=$this->transEsc('query time')?>: <?=$this->localizedNumber($qtime, 2) . $this->transEsc('seconds_abbrev')?>
      <?php endif; ?> -->
      <br><label>Click on a course to see items on reserve</label>
    </div>

    <?php if ($recordTotal > 0): ?>
      <div class="pull-right flip">
        <?=$this->render('search/controls/sort.phtml')?>
      </div>
    <?php endif; ?>
  </div>
  <?php if ($recordTotal < 1): ?>
    <p><?=var_dump($recordTotal); ?>
    <p class="error"><?=$this->translate('nohit_lookfor_html', ['%%lookfor%%' => $this->escapeHtml($reservesLookfor)]) ?></p>
    <?php if (isset($this->parseError)): ?>
      <p class="error"><?=$this->transEsc('nohit_parse_error')?></p>
    <?php endif; ?>
  <?php else: ?>
   <table id="reserves-table" class="table table-striped">
    <tr>
      <th class="department"><?=$this->transEsc('Department')?></th>
      <th class="course_code">Course Number</th>
      <th class="course"><?=$this->transEsc('Course')?></th>
      <th class="instructor"><?=$this->transEsc('Instructor')?></th>
      <th class="section">Section</th>
      <th class="items"><?=$this->transEsc('Items')?></th>
    </tr>
    <?php foreach ($this->results->getResults() as $record): ?>
      <?php
          $url = $this->currentPath() . $this->escapeHtmlAttr(
              '?inst=' . urlencode($record->getInstructorId())
              . '&course=' . urlencode($record->getCourseId())
              . '&dept=' . urlencode($record->getDepartmentId())
      );
	  $url2 = $this->currentPath() . $this->escapeHtmlAttr(
		  '?type=AllFields&filter%5B%5D=department_str%3A%22' . urlencode($record->getDepartment())
	  );
	  $url3 = $this->currentPath() . $this->escapeHtmlAttr(
		  '?type=AllFields&filter%5B%5D=instructor_str%3A%22' . urlencode($record->getInstructor())
	  );
      ?>
      <tr>
	<td class="department"><a href="<?=$url2?>"><?=$this->escapeHtml($record->getDepartment())?></a></td>
        <td class="course_code"><a href="<?=$url?>"><?=$this->escapeHtml($record->getCourseCode())?></a></td>
	<td class="course"><a href="<?=$url?>"><?=$this->escapeHtml($record->getCourse())?></a></td>
        <td class="instructor"><a href="<?=$url3?>"><?=$this->escapeHtml($record->getInstructor())?></a></td>
        <td class="section"><?=$this->escapeHtml($record->getSection())?></td>
        <td class="items"><a href="<?=$url?>"><?=$this->escapeHtml($record->getItemCount())?></a></td>
      </tr>
    <?php endforeach; ?>
    </table>
    <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results])?>
  <?php endif; ?>
</div>

<?php /* Narrow Search Options */ ?>
<div class="<?=$this->layoutClass('sidebar')?>">
<h4>For Faculty</h4>
<div class="facet-group">
    <ul id="helpful-links">
	<li><a href="https://beatleyweb.simmons.edu/reserves/index.html" class="link-sidebar js-facet-item facetAND" target="_blank">Add an item to your course</a></li>
	<li><a href="https://beatleyweb.simmons.edu/reserves/RemoveAnItem.html" class="link-sidebar js-facet-item facetAND" target="_blank">Remove an item from your course</a></li>
        <li><a href="http://courses.simmons.edu/summer/b" class="link-sidebar js-facet-item facetAND" target="_blank">Course schedule</a></li>
    </ul>
</div>
  <?php foreach ($this->results->getRecommendations('side') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>
</div>
<?php /* End Narrow Search Options */ ?>
